services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smartcam
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: smartcam
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: smartcam
      FERNET_KEY: ""
      HF_TOKEN: ""
      HF_MODELS: "{}"
      STREAM_TEMPLATE: "rtsp://{user}:{password}@{ip}/live0"
    volumes:
      - ./storage:/app/storage
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
